name: API Integration Tests

on:
  schedule:
    # Run Monday to Friday at 11:00 AM UTC (12:00 PM UK time)
    - cron: '0 11 * * 1-5'
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to test'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - dev
        - staging

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run integration tests
      env:
        TEST_ENV: ${{ github.event.inputs.environment || 'prod' }}
        API_USERNAME: admin
        API_PASSWORD: password123
      run: |
        pytest tests/ -v -s -n0

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ github.event.inputs.environment || 'prod' }}
        path: reports/
        retention-days: 7
